var $jscomp={scope:{},findInternal:function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var g=a[e];if(c.call(b,g,e,a))return{i:e,v:g}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");var MAX_DIVIDEND,SOUND_URL,DEFAULT,_LS,_LIC=8,_lastResult,sideUserTitle,resetTimer,currentLottery,accountTimer,userparams,betting=!1,doingbet=false,_lastBetsTimer,_resultTimer;$.ajaxSetup({cache:!1});
$(function(){if(/MSIE (6|7)/.test(navigator.userAgent)){var a=function(){var a=$("#footer").position().top-$("#main").position().top;$("#main").height(a);$("#frame").height($("#main").height());$("#main .frame").width($("#main").width()-232)};a();$(window).resize(a)}$("#header .menu2 a").click(function(){$("#header .menu2 a.selected,#header .sub a.selected").removeClass("selected");$(this).addClass("selected");var a=$(this).attr("href");if(null!=a&&-1!=a.indexOf("{lottery}"))return a=a.replace("{lottery}",
currentLottery.id),$("#"+$(this).attr("target")).attr("src",a),!1});var a=$("#lotterys a").click(function(){var mylotid=$(this).attr("id");if( ",l_BJKL8,l_F3D,l_PL3,l_GXK3,l_GXKLSF,l_GD11X5,".indexOf(mylotid)>0 || mylotid=='l_BJPK10BJL' ){alert("\u656c\u8bf7\u671f\u5f85");return false;}changePage($(this));refreshMenu()}).not("[target]").eq(0),c=LIBS.cookie("defaultLT");c&&(c=$("#l_"+c),0<c.length&&(a=c));initMenu();$(".header .sub a").click(function(){var a=$(this);$("#header .menu2 a.selected,#header .sub a.selected").removeClass("selected");$(this).addClass("selected");var c=a.attr("href");$("#frame").attr("src",c).data("a",a);return!1});$(".sidenavibtn").click(function(){var a=
$(this);$(".sidenavibtn").removeClass("sidenaviactive");$(a).addClass("sidenaviactive");var c=a.attr("rel");$("#frame").attr("src",c).data("a",a);return!1});$("#frame").on("load",function(){resetPanel(!0);var a=LIBS.cookie("_skin_");a||(a=getDefaultSkin())||(a=skins[1][0]);a=["blue","gold","red"].indexOf(a);$(".themeicon").eq(a).click()});sideUserTitle=$("#side .user_info .title");sideUserTitle.data("text",sideUserTitle.text());LIBS.get("params",function(a){if(a){for(var b={},c=0;c<a.length;c++){var g=
a[c];b[g.l+"-"+g.g]=g}userparams=b}});$("#betAmount").keypress(function(a){13==a.keyCode&&$("#btnBet").click()});a.click();(a=LIBS.getUrlParam("page"))&&$("#frame").attr("src",a);showAccount()});
function initMenu(){$(".header .lotterys .show");var a=[];$("#lotterys").find("a").each(function(){var b=$(this),c={id:b.attr("id").substr(2),info:b.attr("lang").split("_",2),name:b.text()};b.data("info",c);a.push(c)});var c=LIBS.cookie("_menu_"),b=LIBS.cookie("_menumore_");if(c){for(var d=c.split(","),e=b.split(","),g=d.length,h=$(".lotterys a").length,b=0;b<g;b++){var k=d[b];$(".items").append("<li><div class='item'></div></li>");c=$(".item").eq(b);$("#l_"+k).appendTo(c);$(c).append("<div class='removebtn'></div>")}d=
0;for(b=g;b<h;b++)k=e[d],$(".gamebox").append("<div class='itemmg'></div>"),c=$(".itemmg").eq(d),$("#l_"+k).appendTo(c),$(c).append("<div class='addbtn'></div>"),d++}else{d=Math.min(_LIC,a.length);for(b=0;b<d;b++)$(".items").append("<li><div class='item'></div></li>"),c=$(".item").eq(b),$("#l_"+a[b].id).appendTo(c),$(c).append("<div class='removebtn'></div>");d=0;for(b=_LIC;b<a.length;b++)$(".gamebox").append("<div class='itemmg'></div>"),c=$(".itemmg").eq(d),$("#l_"+a[b].id).appendTo(c),$(c).append("<div class='addbtn'></div>"),
d++}$("#footer .more").click(function(){var a=$("#moreNotice");0==a.length&&(a=$('<div id="moreNotice">'),a.dialog({autoOpen:!1,modal:!0,title:"\u5386\u53f2\u516c\u544a",width:800,height:500,buttons:{"\u5173\u95ed":function(){$(this).dialog("close")}}}));a.empty().load("notices");a.dialog("open")})}function changePage(a,c){if(!a.attr("target")){var b=a.data("info");LIBS.cookie("defaultLT",b.id);currentLottery&&b.id==currentLottery.id||(currentLottery=b,refreshBets());b=$("#sub_"+b.id);$(".header .sub div:visible").hide();b.show();var d;void 0!==c?d=b.find("a:eq("+c+")"):(d=b.find("a.default"),0==d.length&&(d=b.find("a:eq(0)")));d.click()}}
function refreshBets(){clearTimeout(_lastBetsTimer);currentLottery&&(LIBS.get("lasts?lottery="+currentLottery.id,function(a){if(a)for(var c=$("#lastBets ul").empty(),b=0;b<a.length;b++){var d=a[b],e=$("<li>").appendTo(c);e.append($("<p>").html('\u6ce8\u5355\u53f7\uff1a<br/><span class="bid">'+d.id+"#</span>"));e.append($("<p>").addClass("contents").html('<span class="text">'+d.t+'</span>@<span class="odds">'+d.o+"</span>"));e.append($("<p>").text("\u4e0b\u6ce8\u989d\uff1a\uffe5"+d.a))}}),_lastBetsTimer=
setTimeout(refreshBets,6E4))}function playSound(){if(SOUND_URL){var a=$("#SOUND");0==a.length?(a=$('<audio id="SOUND"><source src="'+SOUND_URL+'" type="audio/mpeg"/></audio>').appendTo($("body"))[0],a.load&&a.load()):a=a[0];a.play&&a.play()}}function bet(a,c,b,d){postBet({lottery:a,drawNumber:c,bets:b},d)}
function postBet(a,c){a.bets.toJSON=function(){for(var a=[],c=0;c<this.length;c++)a[c]=LIBS.clone({},this[c],"game contents amount odds multiple mcount state".split(" "));return a};return $.ajax({url:"/member/bet",type:"POST",contentType:"application/json",data:JSON.stringify(a),success:function(b){doingbet=false;try{if($.isFunction(c)&&!1===c(b))return}catch(d){}showBetResult(a,b)},error:function(a){doingbet=false;alert("\u6295\u6ce8\u5931\u8d25\uff1a"+a.code+",\u8bf7\u68c0\u67e5\u4e0b\u6ce8\u72b6\u51b5\u5f8c\u91cd\u8bd5\u3002")},complate:function(){doingbet=false;toggleBetButton(!0)}})}
function showAccount(a){clearTimeout(accountTimer);accountTimer=setTimeout(function(){LIBS.get("account",function(a){var b=$("#frame")[0].contentWindow.PeriodPanel;b?b.showAccount(a):showAccount(a)})},15E3);a&&($("#account .balance").text(LIBS.round(a.balance,3)),$("#account .betting").text(a.betting||0),0<a.bonus?($("#redPackIcon").show(),loadBonus()):$("#redPackIcon").hide())}
function showResult(a){var c=currentLottery,b=c.info[0];clearTimeout(_resultTimer);_resultTimer=setTimeout(function(){LIBS.get("lastResult?lottery="+c.id,showResult)},3E4);if(a&&a.lottery==c.id){!_lastResult||_lastResult.lottery!=a.lottery||_lastResult.result==a.result&&_lastResult.drawNumber==a.drawNumber||(playSound(),$("#resultList").is(":visible")&&$("#resultFrame")[0].contentWindow.location.reload(!0));_lastResult=a;var d="#";/*_DRAW_URLS[c.id];*/"undefined"!==typeof window.IS_MOBILE?($("#result_balls").attr("href",
d),$("#result_info").html("<strong>"+a.drawNumber+"</strong>\u671f")):($("#result_balls").attr("href",d),$("#result_info").html("<div>"+c.name+"</div><div>"+a.drawNumber+"\u671f\u5f00\u5956</div>"));d=$("#result_balls").attr("class","T_"+b+" L_"+c.id);"HK6"==b||"3D"==b||"KL8"==b?$("#result_balls").css("margin-top","5px"):$("#result_balls").css("margin-top","-5px");d.empty();var e=a.result.split(",");a=a.resultOther.split(",");var g;"HK6"==b?g=get_animal_by_ball:"3D"==b&&(g=function(a,b){return["\u4f70",
"\u62fe","\u4e2a"][b]});for(var h=0;h<e.length;h++){var k=e[h],f=$("<span>").appendTo(d);f.append($("<b>").addClass("b"+k).text(k));g&&f.append($("<i>").text(g(k,h)));"PCEGG"==b&&(h<e.length-1?f.append($('<i style="margin:-25px 0px 0px 40px">').text("+")):(f.append($('<i style="margin:-25px 0px 0px 40px">').text("=")),k=Number(e[0])+Number(e[1])+Number(e[2]),$("<span>").appendTo(d).append($("<b>").addClass("bg b_"+k).text(k))));"HK6"==b&&5==h&&$("<span>").addClass("plus").text("+").appendTo(d)}if(0<
a.length)for(g=$("<div>").addClass("result_stat clearfix").appendTo(d),"GXKLSF"==b?g=$("<div>").addClass("result_stat clearfix ml8").appendTo(d):"PK10"!=b&&(g=$("<div>").addClass("result_stat clearfix ml4").appendTo(d)),h=0;h<a.length;h++)(b=a[h])&&g.append($("<div>").addClass("statitm").text(b))}}function getUserParam(a,c){if(userparams)return userparams[a+"-"+c]}
function toggleBetButton(a){a?($(".control input").hide(),$(".control span").show()):($(".control span").hide(),$(".control input").show())}function getBetTextHtml(a){function c(a,b){return'<span class="text">'+a+'</span>@<span class="odds">'+b+"</span>"}if(a.multiple)return c(a.title,a.odds);var b=a.text,d=b.split("@");a.title&&(b=a.title+" "+d[0]);b=c(b,a.odds);if(1<d.length)for(var e=1;e<d.length;e++)b+="<br />"+c(d[e],a.oddsDetail[e-1]);return b}
function showBetResult(a,c){if(3==c.status)alert(c.message);else{showAccount(c.account);$("#betResultDrawNumber").text(a.drawNumber+"\u671f");var b=$("#betReulstList");b.empty();var d=a.bets,e=0,g=0,h=c.message;1==c.status?(h="\u8d54\u7387\u53d8\u66f4",$("#btnBetRetry").removeClass("disabled").prop("disabled",!1).data("last",a)):(2==c.status&&(h="\u540e\u53f0\u672a\u5f00\u76d8,\u4e0d\u53ef\u4ee5\u4e0b\u6ce8"),$("#btnBetRetry").addClass("disabled").prop("disabled",!0));for(var k=0;k<d.length;k++){var f=
d[k],l=c.odds[k].split(","),q=l.shift();f.odds=q;f.oddsDetail=l;l=$("<li>").appendTo(b);0==c.status&&l.append($("<p>").html('\u6ce8\u5355\u53f7\uff1a<span class="bid">'+c.ids[k]+"</span>"));l.append($("<p>").addClass("contents").html(getBetTextHtml(f)));if(1<f.multiple){g+=f.multiple;e+=f.amount*f.multiple;l.append($("<p>").addClass("contents").text("\u590d\u5f0f\u300e "+f.multiple+" \u7ec4 \u300f"));l.append($("<p>").addClass("contents").text(f.text.join("\u3001")));var n=f.amount;l.append($("<p>").text("\u5206\u3000\u7ec4\uff1a"+
n+" \u00d7 "+f.multiple+"\u7ec4"));l.append($("<p>").text("\u5408\u8ba1\u989d\uff1a"+f.amount*f.multiple));l.append($("<p>").text("\u53ef\u8d62\u989d\uff1a"+LIBS.round(n*f.odds-n,1)));var r=$("<table>").appendTo(l),m=$("<tr>").addClass("head").appendTo(r);m.append($("<th>").text("ID").addClass("id"));m.append($("<th>").text("\u53f7\u7801\u7ec4\u5408").addClass("nums"));m.append($("<th>").text("\u4e0b\u6ce8\u989d"));for(var m=LIBS.comboArray(f.text,f.mcount),p=0;p<m.length;p++)$("<tr>").appendTo(r).append($("<td>").text(p+
1)).append($("<td>").text(m[p].join(","))).append($("<td>").text("\uffe5 "+n).addClass("amount"))}else g+=1,e+=f.amount,f.multiple&&l.append($("<p>").addClass("contents").text(f.text.join("\u3001"))),l.append($("<p>").text("\u4e0b\u6ce8\u91d1\u989d\uff1a "+f.amount)),l.append($("<p>").text("\u53ef\u8d62\u91d1\u989d\uff1a "+LIBS.round(f.amount*f.odds-f.amount,1,!0)));(1<c.status||1==c.status&&q!=f.odds)&&l.append($("<span>").addClass("errmsg").text(h))}b=$("#betResultPanel");0==c.status?($("#betResultCount").text(g+
"\u7b14"),$("#betResultTotal").text(e),b.children(".s1").hide(),b.children(".s0").show()):(b.children(".s0").hide(),b.children(".s1").show());showPanel(b,"\u4e0b\u6ce8\u7ed3\u679c\u53cd\u9988")}}function reBet(a){a=$(a).data("last");null!=a&&(a.ignore=!0,postBet(a))}function showPanel(a,c){resetPanel();sideUserTitle.text(c);$(".betdone").hide();a.show()}
function resetPanel(a){clearTimeout(resetTimer);resetTimer=null;sideUserTitle.text(sideUserTitle.data("text"));$(".betdone").show();$("#betResultPanel").hide();a||refreshBets()}
function showMsg(a,c){var b=$("#messageBox");0==b.length&&(b=$('<div id="messageBox">').appendTo("body").dialog({autoOpen:!1,resizable:!1,modal:!0,icon:!0,minHeight:0,width:400,title:"\u7528\u6237\u63d0\u793a",buttons:{"\u786e\u5b9a":function(){$(this).data("ok",!0).dialog("close")},"\u53d6\u6d88":function(){$(this).dialog("close")}}}).on("dialogclose",function(a){a=$(this).data("cb");$.isFunction(a)&&a($(this).data("ok"))}));b.text(a).dialog("open").data({ok:!1,cb:c});c?b.dialog("widget").find(".ui-dialog-buttonset button:eq(1)").show():
b.dialog("widget").find(".ui-dialog-buttonset button:eq(1)").hide()}function getBetText(a){var c="";a.title&&(c+=a.title+" ");c+=a.text;if(a.multiple&&1<a.multiple){c+='<div class="multiple">\u590d\u5f0f\u300e <span>'+a.multiple+' \u7ec4</span> \u300f&nbsp;<a>\u67e5\u770b\u660e\u7ec6</a><ol style="display:none">';a=LIBS.comboArray(a.text,a.mcount);for(var b=0;b<a.length;b++)c+="<li><span>"+a[b].join("\u3001")+"<span></li>";c+="</ol>"}return c}
function isNum3(a){a=a?a:window.event;a=a.which?a.which:a.keyCode;if(a==45||a==58) return true;return 32<a&&(47>a||57<a)?!1:!0}function showBets(a,c){function b(){var a=0,b=0;e.find("tr").each(function(){var c=$(this);if(0!=c.find("input:checked").length){var d=Number(c.find(".amount input").val());0>=d||isNaN(d)||(c=c.data("b"),c=c.multiple?c.multiple:1,a+=d*c,b+=c)}});$("#bcount").text("\u7ec4\u6570\uff1a"+b);$("#btotal").text("\u603b\u91d1\u989d\uff1a"+a)}var d=$("#betsBox");0==d.length&&(d=$('<div id="betsBox"></div>').appendTo("body").dialog({closeButton:!1,autoOpen:!1,resizable:!1,icon:!0,modal:!0,minHeight:0,width:400,
title:"\u4e0b\u6ce8\u660e\u7ec6\uff08\u8bf7\u786e\u8ba4\u6ce8\u5355\uff09",buttons:{"\u786e\u5b9a":function(){if(doingbet==false){doingbet=true;}else{return;}var a=[];$("#betList tr").each(function(){var b=$(this);if(0!=b.find("input:checked").length){var c=Number(b.find(".amount input").val());0>=c||isNaN(c)||(b=b.data("b"),b.amount=c,a.push(b))}});if(0<a.length){var b=$(this).data("req");b.bets=a;postBet(b,$(this).data("cb"))};$(this).data("sc",!0).dialog("close")},"\u53d6\u6d88":function(){$(this).dialog("close")}}}).on("dialogclose",function(){betting=
!1}).on("dialogopen",function(){doingbet=false;}).on("dialogbeforeclose",function(){if(!$(this).data("sc")){var a=$(this);showMsg("\u4f60\u786e\u5b9a\u53d6\u6d88\u4e0b\u6ce8\u5417\uff1f",function(b){b&&a.data("sc",!0).dialog("close")});return!1}}).html('<div class="betList"><table class="table"><thead><th>\u53f7\u7801</th><th>\u8d54\u7387</th><th>\u91d1\u989d</th><th>\u786e\u8ba4</th></thead><tbody id="betList"></tbody></table></div><div class="bottom"><span id="bcount"></span><span id="btotal"></span></div>'),d.keypress(function(a){13==a.keyCode&&
$(this).parent().find(".ui-dialog-buttonset button:eq(0)").click()}));betting=!0;var e=$("#betList");e.empty();for(var g=a.bets,h=0,k=g.length;h<k;h++){var f=g[h];$("<tr>").appendTo(e).data("b",f).append($("<td>").addClass("contents").html(getBetText(f))).append($("<td>").addClass("odds").text(f.odds)).append($("<td>").addClass("amount").append($("<input onkeypress='return isNum3(event)'>").val(f.amount))).append($("<td>").addClass("check").append($('<input type="checkbox">').prop("checked",!0)))}e.find("input").change(b);e.find(".multiple a").hover(function(){$(this).parent().find("ol").show()},
function(){$(this).parent().find("ol").hide()});b();d.dialog("open").data({req:a,sc:!1,cb:c})}function refreshMenu(){$(".gamecontainer").hide();var a=$("#l_"+currentLottery.id);$("#items a.selected").removeClass("selected");a.parent().hasClass("itemmg")?($("#moregames").text(a.data("info").name),$(".lotterys .menumoregame").addClass("selected2")):($("#moregames").text("\u66f4\u591a\u6e38\u620f"),$(".lotterys .menumoregame").removeClass("selected2"),a.addClass("selected"))}
$(document).on("click",".removebtn",function(){var a=$(".item").length;if(1==a)showMsg("\u6700\u5c11\u8981\u4fdd\u7559\u4e00\u4e2a\u6e38\u620f\uff01");else{var c=$(this).parent().find("a"),a=$(".itemmg").length;$(".gamebox").append("<div class='itemmg'></div>");$(c).appendTo(".itemmg:eq("+a+")");$(".itemmg:eq("+a+")").append("<div class='addbtn'></div>");$(this).parent().parent().remove();$(".addbtn").css("display","block");$(".removebtn").css("display","block")}});
$(document).on("click",".addbtn",function(){var a=$(".item").length;if(a==_LIC)showMsg("\u6700\u591a\u53ef\u4ee5\u6dfb\u52a0"+_LIC+"\u4e2a\u6e38\u620f\uff01");else{var c=$(this).parent().find("a");$(".items").append("<li class='ui-sortable-handle'><div class='item'></div></div>");$(c).appendTo(".item:eq("+a+")");$(".item:eq("+a+")").append("<div class='removebtn'></div>");$(this).parent().remove()}$(".addbtn").css("display","block");$(".removebtn").css("display","block")});
function loadAccount(){var a=$("#frame")[0].contentWindow.PeriodPanel;a&&a.loadAccounts()}function loadBonus(){$.getJSON("payment/getbonusinfo",function(a){a.data&&(1<a.data.length?(9<a.data.length?$("#redPackIcon .redpack_no span").text("9+"):$("#redPackIcon .redpack_no span").text(a.data.length),$("#redPackIcon .redpack_no").show()):1==a.data.length&&$("#redPackIcon .redpack_no").hide())})}$(function(){$("#resultList").draggable();$("a").click(function(){$("#resultList").hide()})});
